-- Safari Njema: the whole database in one file. Generated by scripts/buildSetupSql.ts. Do not edit by hand.
-- Paste this once into the Supabase SQL editor of a NEW project and press Run. It is not meant to be run twice.

-- ===== 0001_tables.sql =====
-- All tables from section 8 of the PRD. Policies are in 0002, functions in 0003.
-- Exists as the single starting schema for Safari Njema v2.

create extension if not exists "pgcrypto";

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  swahili_level text not null default 'none' check (swahili_level in ('none', 'some', 'classes')),
  is_demo boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.user_settings (
  user_id uuid primary key references auth.users (id) on delete cascade,
  theme_mode text not null default 'system' check (theme_mode in ('system', 'light', 'dark')),
  palette_key text not null default 'marigold',
  custom_accent text,
  sheng_enabled boolean not null default false
);

create table public.trips (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  title text not null default 'My trip to Kenya',
  start_date date,
  end_date date,
  trip_styles text[] not null default '{}',
  created_at timestamptz not null default now()
);
create index trips_user_id_idx on public.trips (user_id);

create table public.places (
  id uuid primary key default gen_random_uuid(),
  google_place_id text not null unique,
  name text not null,
  lat numeric not null,
  lng numeric not null,
  google_types text[] not null default '{}',
  place_type text not null,
  region text not null
);

create table public.trip_stops (
  id uuid primary key default gen_random_uuid(),
  trip_id uuid not null references public.trips (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  place_id uuid not null references public.places (id),
  visit_date date,
  activities text[] not null default '{}',
  position int not null default 0,
  lesson_status text not null default 'generating' check (lesson_status in ('generating', 'ready', 'failed')),
  created_at timestamptz not null default now()
);
create index trip_stops_trip_id_idx on public.trip_stops (trip_id);
create index trip_stops_user_id_idx on public.trip_stops (user_id);

create table public.phrases (
  id uuid primary key default gen_random_uuid(),
  swahili text not null,
  pronunciation text not null default '',
  english text not null,
  tags text[] not null default '{}',
  register text not null default 'standard' check (register in ('standard', 'sheng', 'coastal')),
  accepted_variants text[] not null default '{}',
  verified boolean not null default false,
  source text,
  audio_path text
);
create index phrases_tags_idx on public.phrases using gin (tags);

create table public.proverbs (
  id uuid primary key default gen_random_uuid(),
  swahili text not null,
  meaning text not null,
  themes text[] not null default '{}'
);

-- The shared lesson cache. One row per place, activity set and level.
create table public.lessons (
  id uuid primary key default gen_random_uuid(),
  place_id uuid not null references public.places (id),
  activities_key text not null default '',
  level text not null default 'none',
  content jsonb not null,
  generated_by text not null,
  created_at timestamptz not null default now()
);
create index lessons_cache_idx on public.lessons (place_id, activities_key, level);

create table public.user_lessons (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  trip_stop_id uuid not null references public.trip_stops (id) on delete cascade,
  lesson_id uuid not null references public.lessons (id),
  status text not null default 'ready' check (status in ('ready', 'started', 'completed')),
  current_step int not null default 0,
  score int,
  duration_seconds int,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);
create index user_lessons_user_id_idx on public.user_lessons (user_id);
create index user_lessons_trip_stop_id_idx on public.user_lessons (trip_stop_id);

create table public.phrase_progress (
  user_id uuid not null references auth.users (id) on delete cascade,
  phrase_id uuid not null references public.phrases (id) on delete cascade,
  box int not null default 1,
  due_date date,
  times_correct int not null default 0,
  times_wrong int not null default 0,
  best_speaking_score numeric,
  used_in_real_life boolean not null default false,
  primary key (user_id, phrase_id)
);

create table public.speaking_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  phrase_id uuid not null references public.phrases (id) on delete cascade,
  transcript text,
  score numeric,
  passed boolean,
  method text check (method in ('auto', 'self')),
  created_at timestamptz not null default now()
);

create table public.phrase_reports (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  phrase_id uuid not null references public.phrases (id) on delete cascade,
  note text,
  created_at timestamptz not null default now()
);

create table public.user_kangas (
  user_id uuid not null references auth.users (id) on delete cascade,
  user_lesson_id uuid not null references public.user_lessons (id) on delete cascade,
  proverb_id uuid not null references public.proverbs (id),
  earned_at timestamptz not null default now(),
  primary key (user_id, user_lesson_id)
);

-- ===== 0002_policies.sql =====
-- Row Level Security for every table. Users see only their own rows.
-- Shared content (phrases, proverbs, places, lessons) is readable by signed in users and written only by Edge Functions.

alter table public.profiles enable row level security;
alter table public.user_settings enable row level security;
alter table public.trips enable row level security;
alter table public.places enable row level security;
alter table public.trip_stops enable row level security;
alter table public.phrases enable row level security;
alter table public.proverbs enable row level security;
alter table public.lessons enable row level security;
alter table public.user_lessons enable row level security;
alter table public.phrase_progress enable row level security;
alter table public.speaking_attempts enable row level security;
alter table public.phrase_reports enable row level security;
alter table public.user_kangas enable row level security;

-- Own row tables.
create policy "own profile" on public.profiles for all to authenticated using (auth.uid() = id) with check (auth.uid() = id);
create policy "own settings" on public.user_settings for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own trips" on public.trips for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own stops" on public.trip_stops for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own lessons" on public.user_lessons for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own progress" on public.phrase_progress for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own attempts" on public.speaking_attempts for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own reports" on public.phrase_reports for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own kangas" on public.user_kangas for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Shared content: read only for signed in users. The service role key bypasses RLS for writes.
create policy "read phrases" on public.phrases for select to authenticated using (true);
create policy "read proverbs" on public.proverbs for select to authenticated using (true);
create policy "read places" on public.places for select to authenticated using (true);
create policy "read lessons" on public.lessons for select to authenticated using (true);

-- ===== 0003_functions.sql =====
-- Two database functions: create profile rows for new users, and add a stop in one call.
-- add_trip_stop runs as the owner so users can upsert places without a write policy on that table.

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name) values (new.id, split_part(new.email, '@', 1));
  insert into public.user_settings (user_id) values (new.id);
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create or replace function public.add_trip_stop(
  p_trip_id uuid,
  p_google_place_id text,
  p_name text,
  p_lat numeric,
  p_lng numeric,
  p_google_types text[],
  p_place_type text,
  p_region text,
  p_visit_date date,
  p_activities text[]
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_place_id uuid;
  v_stop_id uuid;
  v_position int;
begin
  if not exists (select 1 from public.trips where id = p_trip_id and user_id = auth.uid()) then
    raise exception 'Trip not found';
  end if;

  insert into public.places (google_place_id, name, lat, lng, google_types, place_type, region)
  values (p_google_place_id, p_name, p_lat, p_lng, p_google_types, p_place_type, p_region)
  on conflict (google_place_id) do update
    set name = excluded.name, lat = excluded.lat, lng = excluded.lng,
        google_types = excluded.google_types, place_type = excluded.place_type, region = excluded.region
  returning id into v_place_id;

  select coalesce(max(position), 0) + 1 into v_position from public.trip_stops where trip_id = p_trip_id;

  insert into public.trip_stops (trip_id, user_id, place_id, visit_date, activities, position, lesson_status)
  values (p_trip_id, auth.uid(), v_place_id, p_visit_date, coalesce(p_activities, '{}'), v_position, 'generating')
  returning id into v_stop_id;

  return v_stop_id;
end;
$$;

grant execute on function public.add_trip_stop to authenticated;

-- ===== 0004_phrase_sort_order.sql =====
-- Adds a teaching order to the phrase bank. When two phrases fit a stop equally well, the earlier one in v1 wins.
-- No new table, so no new policies. The existing read policy on phrases covers this column.

alter table public.phrases add column sort_order int not null default 0;
create index phrases_sort_order_idx on public.phrases (sort_order);

-- ===== seed.sql: 95 reviewed phrases and 10 proverbs =====
-- Generated by scripts/buildSeedSql.ts from supabase/seed/*.json. Do not edit by hand.
-- Runs again safely: rows are matched on their Swahili text.
update public.phrases set verified = true, tags = array['basics', 'greeting', 'core_greeting', 'essential']::text[], register = 'standard', sort_order = 1 where swahili = 'Habari?' and english = 'How are you? (literally: news?)';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Habari?', 'ha-BA-ri', 'How are you? (literally: news?)', array['basics', 'greeting', 'core_greeting', 'essential']::text[], 'standard', array[]::text[], true, 'v1 chapter salamu: Greetings first', 1 where not exists (select 1 from public.phrases where swahili = 'Habari?' and english = 'How are you? (literally: news?)');
update public.phrases set verified = true, tags = array['basics', 'greeting', 'core_greeting', 'essential']::text[], register = 'standard', sort_order = 2 where swahili = 'Nzuri' and english = 'Good. The standard reply to Habari';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Nzuri', 'n-ZU-ri', 'Good. The standard reply to Habari', array['basics', 'greeting', 'core_greeting', 'essential']::text[], 'standard', array[]::text[], true, 'v1 chapter salamu: Greetings first', 2 where not exists (select 1 from public.phrases where swahili = 'Nzuri' and english = 'Good. The standard reply to Habari');
update public.phrases set verified = true, tags = array['basics', 'greeting']::text[], register = 'sheng', sort_order = 3 where swahili = 'Sasa? / Poa' and english = 'What''s up? / Cool (Nairobi slang)';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Sasa? / Poa', 'SA-sa / PO-a', 'What''s up? / Cool (Nairobi slang)', array['basics', 'greeting']::text[], 'sheng', array[]::text[], true, 'v1 chapter salamu: Greetings first', 3 where not exists (select 1 from public.phrases where swahili = 'Sasa? / Poa' and english = 'What''s up? / Cool (Nairobi slang)');
update public.phrases set verified = true, tags = array['basics', 'greeting', 'respect']::text[], register = 'standard', sort_order = 4 where swahili = 'Shikamoo / Marahaba' and english = 'Respectful greeting to an elder / the elder''s reply';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Shikamoo / Marahaba', 'shi-ka-MO / ma-ra-HA-ba', 'Respectful greeting to an elder / the elder''s reply', array['basics', 'greeting', 'respect']::text[], 'standard', array[]::text[], true, 'v1 chapter salamu: Greetings first', 4 where not exists (select 1 from public.phrases where swahili = 'Shikamoo / Marahaba' and english = 'Respectful greeting to an elder / the elder''s reply');
update public.phrases set verified = true, tags = array['basics', 'polite', 'essential']::text[], register = 'standard', sort_order = 5 where swahili = 'Asante sana' and english = 'Thank you very much';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Asante sana', 'a-SAN-te SA-na', 'Thank you very much', array['basics', 'polite', 'essential']::text[], 'standard', array[]::text[], true, 'v1 chapter salamu: Greetings first', 5 where not exists (select 1 from public.phrases where swahili = 'Asante sana' and english = 'Thank you very much');
update public.phrases set verified = true, tags = array['basics', 'polite']::text[], register = 'standard', sort_order = 6 where swahili = 'Karibu' and english = 'Welcome. Also: you''re welcome';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Karibu', 'ka-RI-bu', 'Welcome. Also: you''re welcome', array['basics', 'polite']::text[], 'standard', array[]::text[], true, 'v1 chapter salamu: Greetings first', 6 where not exists (select 1 from public.phrases where swahili = 'Karibu' and english = 'Welcome. Also: you''re welcome');
update public.phrases set verified = true, tags = array['basics', 'polite']::text[], register = 'standard', sort_order = 7 where swahili = 'Tafadhali' and english = 'Please';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Tafadhali', 'ta-fa-DHA-li', 'Please', array['basics', 'polite']::text[], 'standard', array[]::text[], true, 'v1 chapter salamu: Greetings first', 7 where not exists (select 1 from public.phrases where swahili = 'Tafadhali' and english = 'Please');
update public.phrases set verified = true, tags = array['basics', 'polite']::text[], register = 'standard', sort_order = 8 where swahili = 'Samahani' and english = 'Excuse me, sorry';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Samahani', 'sa-ma-HA-ni', 'Excuse me, sorry', array['basics', 'polite']::text[], 'standard', array[]::text[], true, 'v1 chapter salamu: Greetings first', 8 where not exists (select 1 from public.phrases where swahili = 'Samahani' and english = 'Excuse me, sorry');
update public.phrases set verified = true, tags = array['basics']::text[], register = 'standard', sort_order = 9 where swahili = 'Ndiyo / Hapana' and english = 'Yes / No';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Ndiyo / Hapana', 'n-DI-yo / ha-PA-na', 'Yes / No', array['basics']::text[], 'standard', array[]::text[], true, 'v1 chapter salamu: Greetings first', 9 where not exists (select 1 from public.phrases where swahili = 'Ndiyo / Hapana' and english = 'Yes / No');
update public.phrases set verified = true, tags = array['basics']::text[], register = 'standard', sort_order = 10 where swahili = 'Sawa' and english = 'Okay';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Sawa', 'SA-wa', 'Okay', array['basics']::text[], 'standard', array[]::text[], true, 'v1 chapter salamu: Greetings first', 10 where not exists (select 1 from public.phrases where swahili = 'Sawa' and english = 'Okay');
update public.phrases set verified = true, tags = array['basics', 'introductions']::text[], register = 'standard', sort_order = 11 where swahili = 'Jina langu ni Sam' and english = 'My name is Sam';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Jina langu ni Sam', 'JI-na LAN-gu ni', 'My name is Sam', array['basics', 'introductions']::text[], 'standard', array[]::text[], true, 'v1 chapter salamu: Greetings first', 11 where not exists (select 1 from public.phrases where swahili = 'Jina langu ni Sam' and english = 'My name is Sam');
update public.phrases set verified = true, tags = array['basics', 'introductions', 'questions']::text[], register = 'standard', sort_order = 12 where swahili = 'Unaitwa nani?' and english = 'What is your name?';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Unaitwa nani?', 'u-na-IT-wa NA-ni', 'What is your name?', array['basics', 'introductions', 'questions']::text[], 'standard', array[]::text[], true, 'v1 chapter salamu: Greetings first', 12 where not exists (select 1 from public.phrases where swahili = 'Unaitwa nani?' and english = 'What is your name?');
update public.phrases set verified = true, tags = array['basics', 'introductions']::text[], register = 'standard', sort_order = 13 where swahili = 'Ninajifunza Kiswahili' and english = 'I am learning Swahili';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Ninajifunza Kiswahili', 'ni-na-ji-FUN-za ki-swa-HI-li', 'I am learning Swahili', array['basics', 'introductions']::text[], 'standard', array[]::text[], true, 'v1 chapter salamu: Greetings first', 13 where not exists (select 1 from public.phrases where swahili = 'Ninajifunza Kiswahili' and english = 'I am learning Swahili');
update public.phrases set verified = true, tags = array['basics', 'help']::text[], register = 'standard', sort_order = 14 where swahili = 'Sema polepole, tafadhali' and english = 'Speak slowly, please';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Sema polepole, tafadhali', 'SE-ma po-le-PO-le', 'Speak slowly, please', array['basics', 'help']::text[], 'standard', array[]::text[], true, 'v1 chapter salamu: Greetings first', 14 where not exists (select 1 from public.phrases where swahili = 'Sema polepole, tafadhali' and english = 'Speak slowly, please');
update public.phrases set verified = true, tags = array['basics', 'help']::text[], register = 'standard', sort_order = 15 where swahili = 'Sielewi' and english = 'I don''t understand';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Sielewi', 'si-e-LE-wi', 'I don''t understand', array['basics', 'help']::text[], 'standard', array[]::text[], true, 'v1 chapter salamu: Greetings first', 15 where not exists (select 1 from public.phrases where swahili = 'Sielewi' and english = 'I don''t understand');
update public.phrases set verified = true, tags = array['basics', 'farewell']::text[], register = 'standard', sort_order = 16 where swahili = 'Kwaheri' and english = 'Goodbye';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Kwaheri', 'kwa-HE-ri', 'Goodbye', array['basics', 'farewell']::text[], 'standard', array[]::text[], true, 'v1 chapter salamu: Greetings first', 16 where not exists (select 1 from public.phrases where swahili = 'Kwaheri' and english = 'Goodbye');
update public.phrases set verified = true, tags = array['airport']::text[], register = 'standard', sort_order = 17 where swahili = 'Pasipoti' and english = 'Passport';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Pasipoti', 'pa-si-PO-ti', 'Passport', array['airport']::text[], 'standard', array[]::text[], true, 'v1 chapter uwanja: At the airport', 17 where not exists (select 1 from public.phrases where swahili = 'Pasipoti' and english = 'Passport');
update public.phrases set verified = true, tags = array['airport']::text[], register = 'standard', sort_order = 18 where swahili = 'Nimekuja kwa utalii' and english = 'I have come for tourism';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Nimekuja kwa utalii', 'ni-me-KU-ja kwa u-ta-LI-i', 'I have come for tourism', array['airport']::text[], 'standard', array[]::text[], true, 'v1 chapter uwanja: At the airport', 18 where not exists (select 1 from public.phrases where swahili = 'Nimekuja kwa utalii' and english = 'I have come for tourism');
update public.phrases set verified = true, tags = array['airport']::text[], register = 'standard', sort_order = 19 where swahili = 'Nitakaa wiki mbili' and english = 'I will stay two weeks';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Nitakaa wiki mbili', 'ni-ta-KA-a WI-ki m-BI-li', 'I will stay two weeks', array['airport']::text[], 'standard', array[]::text[], true, 'v1 chapter uwanja: At the airport', 19 where not exists (select 1 from public.phrases where swahili = 'Nitakaa wiki mbili' and english = 'I will stay two weeks');
update public.phrases set verified = true, tags = array['airport', 'questions']::text[], register = 'standard', sort_order = 20 where swahili = 'Mizigo yangu iko wapi?' and english = 'Where is my luggage?';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Mizigo yangu iko wapi?', 'mi-ZI-go YAN-gu I-ko WA-pi', 'Where is my luggage?', array['airport', 'questions']::text[], 'standard', array[]::text[], true, 'v1 chapter uwanja: At the airport', 20 where not exists (select 1 from public.phrases where swahili = 'Mizigo yangu iko wapi?' and english = 'Where is my luggage?');
update public.phrases set verified = true, tags = array['airport', 'help', 'questions']::text[], register = 'standard', sort_order = 21 where swahili = 'Choo kiko wapi?' and english = 'Where is the toilet?';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Choo kiko wapi?', 'CHO-o KI-ko WA-pi', 'Where is the toilet?', array['airport', 'help', 'questions']::text[], 'standard', array[]::text[], true, 'v1 chapter uwanja: At the airport', 21 where not exists (select 1 from public.phrases where swahili = 'Choo kiko wapi?' and english = 'Where is the toilet?');
update public.phrases set verified = true, tags = array['airport', 'transport']::text[], register = 'standard', sort_order = 22 where swahili = 'Ninahitaji teksi' and english = 'I need a taxi';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Ninahitaji teksi', 'ni-na-hi-TA-ji TEK-si', 'I need a taxi', array['airport', 'transport']::text[], 'standard', array[]::text[], true, 'v1 chapter uwanja: At the airport', 22 where not exists (select 1 from public.phrases where swahili = 'Ninahitaji teksi' and english = 'I need a taxi');
update public.phrases set verified = true, tags = array['airport']::text[], register = 'standard', sort_order = 23 where swahili = 'Ninahitaji laini ya simu' and english = 'I need a SIM card';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Ninahitaji laini ya simu', 'ni-na-hi-TA-ji la-I-ni ya SI-mu', 'I need a SIM card', array['airport']::text[], 'standard', array[]::text[], true, 'v1 chapter uwanja: At the airport', 23 where not exists (select 1 from public.phrases where swahili = 'Ninahitaji laini ya simu' and english = 'I need a SIM card');
update public.phrases set verified = true, tags = array['airport', 'cash']::text[], register = 'standard', sort_order = 24 where swahili = 'Naweza kubadilisha pesa wapi?' and english = 'Where can I change money?';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Naweza kubadilisha pesa wapi?', 'na-WE-za ku-ba-di-LI-sha PE-sa WA-pi', 'Where can I change money?', array['airport', 'cash']::text[], 'standard', array[]::text[], true, 'v1 chapter uwanja: At the airport', 24 where not exists (select 1 from public.phrases where swahili = 'Naweza kubadilisha pesa wapi?' and english = 'Where can I change money?');
update public.phrases set verified = true, tags = array['airport', 'transport', 'hotel']::text[], register = 'standard', sort_order = 25 where swahili = 'Nipeleke hotelini, tafadhali' and english = 'Take me to the hotel, please';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Nipeleke hotelini, tafadhali', 'ni-pe-LE-ke ho-te-LI-ni', 'Take me to the hotel, please', array['airport', 'transport', 'hotel']::text[], 'standard', array[]::text[], true, 'v1 chapter uwanja: At the airport', 25 where not exists (select 1 from public.phrases where swahili = 'Nipeleke hotelini, tafadhali' and english = 'Take me to the hotel, please');
update public.phrases set verified = true, tags = array['airport', 'price']::text[], register = 'standard', sort_order = 26 where swahili = 'Ni shilingi ngapi?' and english = 'How many shillings is it?';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Ni shilingi ngapi?', 'ni shi-LIN-gi n-GA-pi', 'How many shillings is it?', array['airport', 'price']::text[], 'standard', array[]::text[], true, 'v1 chapter uwanja: At the airport', 26 where not exists (select 1 from public.phrases where swahili = 'Ni shilingi ngapi?' and english = 'How many shillings is it?');
update public.phrases set verified = true, tags = array['transport', 'fare', 'essential']::text[], register = 'standard', sort_order = 27 where swahili = 'Nauli ni ngapi?' and english = 'How much is the fare?';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Nauli ni ngapi?', 'na-U-li ni n-GA-pi', 'How much is the fare?', array['transport', 'fare', 'essential']::text[], 'standard', array[]::text[], true, 'v1 chapter usafiri: Getting around', 27 where not exists (select 1 from public.phrases where swahili = 'Nauli ni ngapi?' and english = 'How much is the fare?');
update public.phrases set verified = true, tags = array['transport']::text[], register = 'standard', sort_order = 28 where swahili = 'Unaenda mjini?' and english = 'Are you going to town?';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Unaenda mjini?', 'u-na-EN-da m-JI-ni', 'Are you going to town?', array['transport']::text[], 'standard', array[]::text[], true, 'v1 chapter usafiri: Getting around', 28 where not exists (select 1 from public.phrases where swahili = 'Unaenda mjini?' and english = 'Are you going to town?');
update public.phrases set verified = true, tags = array['transport']::text[], register = 'standard', sort_order = 29 where swahili = 'Nishushe hapa, tafadhali' and english = 'Drop me here, please';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Nishushe hapa, tafadhali', 'ni-SHU-she HA-pa', 'Drop me here, please', array['transport']::text[], 'standard', array[]::text[], true, 'v1 chapter usafiri: Getting around', 29 where not exists (select 1 from public.phrases where swahili = 'Nishushe hapa, tafadhali' and english = 'Drop me here, please');
update public.phrases set verified = true, tags = array['transport']::text[], register = 'standard', sort_order = 30 where swahili = 'Simama hapa' and english = 'Stop here';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Simama hapa', 'si-MA-ma HA-pa', 'Stop here', array['transport']::text[], 'standard', array[]::text[], true, 'v1 chapter usafiri: Getting around', 30 where not exists (select 1 from public.phrases where swahili = 'Simama hapa' and english = 'Stop here');
update public.phrases set verified = true, tags = array['transport']::text[], register = 'standard', sort_order = 31 where swahili = 'Twende' and english = 'Let''s go';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Twende', 'TWEN-de', 'Let''s go', array['transport']::text[], 'standard', array[]::text[], true, 'v1 chapter usafiri: Getting around', 31 where not exists (select 1 from public.phrases where swahili = 'Twende' and english = 'Let''s go');
update public.phrases set verified = true, tags = array['transport']::text[], register = 'standard', sort_order = 32 where swahili = 'Polepole, tafadhali' and english = 'Slowly, please';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Polepole, tafadhali', 'po-le-PO-le', 'Slowly, please', array['transport']::text[], 'standard', array[]::text[], true, 'v1 chapter usafiri: Getting around', 32 where not exists (select 1 from public.phrases where swahili = 'Polepole, tafadhali' and english = 'Slowly, please');
update public.phrases set verified = true, tags = array['transport', 'directions']::text[], register = 'standard', sort_order = 33 where swahili = 'Kushoto / Kulia' and english = 'Left / Right';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Kushoto / Kulia', 'ku-SHO-to / ku-LI-a', 'Left / Right', array['transport', 'directions']::text[], 'standard', array[]::text[], true, 'v1 chapter usafiri: Getting around', 33 where not exists (select 1 from public.phrases where swahili = 'Kushoto / Kulia' and english = 'Left / Right');
update public.phrases set verified = true, tags = array['transport', 'directions']::text[], register = 'standard', sort_order = 34 where swahili = 'Moja kwa moja' and english = 'Straight ahead';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Moja kwa moja', 'MO-ja kwa MO-ja', 'Straight ahead', array['transport', 'directions']::text[], 'standard', array[]::text[], true, 'v1 chapter usafiri: Getting around', 34 where not exists (select 1 from public.phrases where swahili = 'Moja kwa moja' and english = 'Straight ahead');
update public.phrases set verified = true, tags = array['transport', 'directions']::text[], register = 'standard', sort_order = 35 where swahili = 'Ni mbali?' and english = 'Is it far?';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Ni mbali?', 'ni m-BA-li', 'Is it far?', array['transport', 'directions']::text[], 'standard', array[]::text[], true, 'v1 chapter usafiri: Getting around', 35 where not exists (select 1 from public.phrases where swahili = 'Ni mbali?' and english = 'Is it far?');
update public.phrases set verified = true, tags = array['transport', 'fare']::text[], register = 'standard', sort_order = 36 where swahili = 'Naomba chenji yangu' and english = 'My change, please';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Naomba chenji yangu', 'na-OM-ba CHEN-ji YAN-gu', 'My change, please', array['transport', 'fare']::text[], 'standard', array[]::text[], true, 'v1 chapter usafiri: Getting around', 36 where not exists (select 1 from public.phrases where swahili = 'Naomba chenji yangu' and english = 'My change, please');
update public.phrases set verified = true, tags = array['transport', 'directions']::text[], register = 'standard', sort_order = 37 where swahili = 'Kituo cha treni kiko wapi?' and english = 'Where is the train station?';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Kituo cha treni kiko wapi?', 'ki-TU-o cha TRE-ni KI-ko WA-pi', 'Where is the train station?', array['transport', 'directions']::text[], 'standard', array[]::text[], true, 'v1 chapter usafiri: Getting around', 37 where not exists (select 1 from public.phrases where swahili = 'Kituo cha treni kiko wapi?' and english = 'Where is the train station?');
update public.phrases set verified = true, tags = array['food', 'ordering', 'essential']::text[], register = 'standard', sort_order = 38 where swahili = 'Naomba menyu' and english = 'May I have the menu';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Naomba menyu', 'na-OM-ba MEN-yu', 'May I have the menu', array['food', 'ordering', 'essential']::text[], 'standard', array[]::text[], true, 'v1 chapter chakula: Eating out', 38 where not exists (select 1 from public.phrases where swahili = 'Naomba menyu' and english = 'May I have the menu');
update public.phrases set verified = true, tags = array['food', 'ordering', 'drink']::text[], register = 'standard', sort_order = 39 where swahili = 'Naomba maji' and english = 'Water, please';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Naomba maji', 'na-OM-ba MA-ji', 'Water, please', array['food', 'ordering', 'drink']::text[], 'standard', array[]::text[], true, 'v1 chapter chakula: Eating out', 39 where not exists (select 1 from public.phrases where swahili = 'Naomba maji' and english = 'Water, please');
update public.phrases set verified = true, tags = array['food', 'ordering']::text[], register = 'standard', sort_order = 40 where swahili = 'Ningependa nyama choma na ugali' and english = 'I would like roast meat and ugali';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Ningependa nyama choma na ugali', 'nin-ge-PEN-da NYA-ma CHO-ma na u-GA-li', 'I would like roast meat and ugali', array['food', 'ordering']::text[], 'standard', array[]::text[], true, 'v1 chapter chakula: Eating out', 40 where not exists (select 1 from public.phrases where swahili = 'Ningependa nyama choma na ugali' and english = 'I would like roast meat and ugali');
update public.phrases set verified = true, tags = array['food']::text[], register = 'standard', sort_order = 41 where swahili = 'Nusu kilo' and english = 'Half a kilo';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Nusu kilo', 'NU-su KI-lo', 'Half a kilo', array['food']::text[], 'standard', array[]::text[], true, 'v1 chapter chakula: Eating out', 41 where not exists (select 1 from public.phrases where swahili = 'Nusu kilo' and english = 'Half a kilo');
update public.phrases set verified = true, tags = array['food']::text[], register = 'standard', sort_order = 42 where swahili = 'Bila pilipili' and english = 'Without chili';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Bila pilipili', 'BI-la pi-li-PI-li', 'Without chili', array['food']::text[], 'standard', array[]::text[], true, 'v1 chapter chakula: Eating out', 42 where not exists (select 1 from public.phrases where swahili = 'Bila pilipili' and english = 'Without chili');
update public.phrases set verified = true, tags = array['food']::text[], register = 'standard', sort_order = 43 where swahili = 'Sili nyama' and english = 'I don''t eat meat';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Sili nyama', 'SI-li NYA-ma', 'I don''t eat meat', array['food']::text[], 'standard', array[]::text[], true, 'v1 chapter chakula: Eating out', 43 where not exists (select 1 from public.phrases where swahili = 'Sili nyama' and english = 'I don''t eat meat');
update public.phrases set verified = true, tags = array['food', 'drink']::text[], register = 'standard', sort_order = 44 where swahili = 'Baridi / Moto' and english = 'Cold / Hot';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Baridi / Moto', 'ba-RI-di / MO-to', 'Cold / Hot', array['food', 'drink']::text[], 'standard', array[]::text[], true, 'v1 chapter chakula: Eating out', 44 where not exists (select 1 from public.phrases where swahili = 'Baridi / Moto' and english = 'Cold / Hot');
update public.phrases set verified = true, tags = array['food']::text[], register = 'standard', sort_order = 45 where swahili = 'Chakula ni kitamu sana' and english = 'The food is very tasty';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Chakula ni kitamu sana', 'cha-KU-la ni ki-TA-mu SA-na', 'The food is very tasty', array['food']::text[], 'standard', array[]::text[], true, 'v1 chapter chakula: Eating out', 45 where not exists (select 1 from public.phrases where swahili = 'Chakula ni kitamu sana' and english = 'The food is very tasty');
update public.phrases set verified = true, tags = array['food']::text[], register = 'standard', sort_order = 46 where swahili = 'Nimeshiba' and english = 'I am full';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Nimeshiba', 'ni-me-SHI-ba', 'I am full', array['food']::text[], 'standard', array[]::text[], true, 'v1 chapter chakula: Eating out', 46 where not exists (select 1 from public.phrases where swahili = 'Nimeshiba' and english = 'I am full');
update public.phrases set verified = true, tags = array['food', 'ordering', 'paying']::text[], register = 'standard', sort_order = 47 where swahili = 'Naomba bili' and english = 'The bill, please';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Naomba bili', 'na-OM-ba BI-li', 'The bill, please', array['food', 'ordering', 'paying']::text[], 'standard', array[]::text[], true, 'v1 chapter chakula: Eating out', 47 where not exists (select 1 from public.phrases where swahili = 'Naomba bili' and english = 'The bill, please');
update public.phrases set verified = true, tags = array['food', 'paying']::text[], register = 'standard', sort_order = 48 where swahili = 'Naweza kulipa na M-Pesa?' and english = 'Can I pay with M-Pesa?';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Naweza kulipa na M-Pesa?', 'na-WE-za ku-LI-pa na em-PE-sa', 'Can I pay with M-Pesa?', array['food', 'paying']::text[], 'standard', array[]::text[], true, 'v1 chapter chakula: Eating out', 48 where not exists (select 1 from public.phrases where swahili = 'Naweza kulipa na M-Pesa?' and english = 'Can I pay with M-Pesa?');
update public.phrases set verified = true, tags = array['market', 'numbers']::text[], register = 'standard', sort_order = 49 where swahili = 'Moja, mbili, tatu, nne, tano' and english = 'One, two, three, four, five';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Moja, mbili, tatu, nne, tano', 'MO-ja, m-BI-li, TA-tu, N-ne, TA-no', 'One, two, three, four, five', array['market', 'numbers']::text[], 'standard', array[]::text[], true, 'v1 chapter sokoni: At the market', 49 where not exists (select 1 from public.phrases where swahili = 'Moja, mbili, tatu, nne, tano' and english = 'One, two, three, four, five');
update public.phrases set verified = true, tags = array['market', 'numbers']::text[], register = 'standard', sort_order = 50 where swahili = 'Sita, saba, nane, tisa, kumi' and english = 'Six, seven, eight, nine, ten';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Sita, saba, nane, tisa, kumi', 'SI-ta, SA-ba, NA-ne, TI-sa, KU-mi', 'Six, seven, eight, nine, ten', array['market', 'numbers']::text[], 'standard', array[]::text[], true, 'v1 chapter sokoni: At the market', 50 where not exists (select 1 from public.phrases where swahili = 'Sita, saba, nane, tisa, kumi' and english = 'Six, seven, eight, nine, ten');
update public.phrases set verified = true, tags = array['market', 'numbers']::text[], register = 'standard', sort_order = 51 where swahili = 'Mia / Elfu' and english = 'Hundred / Thousand';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Mia / Elfu', 'MI-a / EL-fu', 'Hundred / Thousand', array['market', 'numbers']::text[], 'standard', array[]::text[], true, 'v1 chapter sokoni: At the market', 51 where not exists (select 1 from public.phrases where swahili = 'Mia / Elfu' and english = 'Hundred / Thousand');
update public.phrases set verified = true, tags = array['market', 'numbers']::text[], register = 'standard', sort_order = 52 where swahili = 'Mia tano' and english = 'Five hundred';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Mia tano', 'MI-a TA-no', 'Five hundred', array['market', 'numbers']::text[], 'standard', array[]::text[], true, 'v1 chapter sokoni: At the market', 52 where not exists (select 1 from public.phrases where swahili = 'Mia tano' and english = 'Five hundred');
update public.phrases set verified = true, tags = array['market', 'bargaining', 'price', 'essential']::text[], register = 'standard', sort_order = 53 where swahili = 'Hii ni bei gani?' and english = 'What is the price of this?';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Hii ni bei gani?', 'HI-i ni BE-i GA-ni', 'What is the price of this?', array['market', 'bargaining', 'price', 'essential']::text[], 'standard', array[]::text[], true, 'v1 chapter sokoni: At the market', 53 where not exists (select 1 from public.phrases where swahili = 'Hii ni bei gani?' and english = 'What is the price of this?');
update public.phrases set verified = true, tags = array['market', 'bargaining']::text[], register = 'standard', sort_order = 54 where swahili = 'Ni ghali sana' and english = 'It is too expensive';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Ni ghali sana', 'ni GHA-li SA-na', 'It is too expensive', array['market', 'bargaining']::text[], 'standard', array[]::text[], true, 'v1 chapter sokoni: At the market', 54 where not exists (select 1 from public.phrases where swahili = 'Ni ghali sana' and english = 'It is too expensive');
update public.phrases set verified = true, tags = array['market', 'bargaining', 'essential']::text[], register = 'standard', sort_order = 55 where swahili = 'Punguza bei, tafadhali' and english = 'Lower the price, please';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Punguza bei, tafadhali', 'pun-GU-za BE-i', 'Lower the price, please', array['market', 'bargaining', 'essential']::text[], 'standard', array[]::text[], true, 'v1 chapter sokoni: At the market', 55 where not exists (select 1 from public.phrases where swahili = 'Punguza bei, tafadhali' and english = 'Lower the price, please');
update public.phrases set verified = true, tags = array['market', 'bargaining']::text[], register = 'standard', sort_order = 56 where swahili = 'Bei ya mwisho ni ngapi?' and english = 'What is your last price?';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Bei ya mwisho ni ngapi?', 'BE-i ya m-WI-sho ni n-GA-pi', 'What is your last price?', array['market', 'bargaining']::text[], 'standard', array[]::text[], true, 'v1 chapter sokoni: At the market', 56 where not exists (select 1 from public.phrases where swahili = 'Bei ya mwisho ni ngapi?' and english = 'What is your last price?');
update public.phrases set verified = true, tags = array['market', 'shopping']::text[], register = 'standard', sort_order = 57 where swahili = 'Naangalia tu' and english = 'I am just looking';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Naangalia tu', 'na-an-ga-LI-a tu', 'I am just looking', array['market', 'shopping']::text[], 'standard', array[]::text[], true, 'v1 chapter sokoni: At the market', 57 where not exists (select 1 from public.phrases where swahili = 'Naangalia tu' and english = 'I am just looking');
update public.phrases set verified = true, tags = array['market', 'shopping']::text[], register = 'standard', sort_order = 58 where swahili = 'Una rangi nyingine?' and english = 'Do you have another colour?';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Una rangi nyingine?', 'U-na RAN-gi nyin-GI-ne', 'Do you have another colour?', array['market', 'shopping']::text[], 'standard', array[]::text[], true, 'v1 chapter sokoni: At the market', 58 where not exists (select 1 from public.phrases where swahili = 'Una rangi nyingine?' and english = 'Do you have another colour?');
update public.phrases set verified = true, tags = array['market', 'shopping']::text[], register = 'standard', sort_order = 59 where swahili = 'Nitachukua hii' and english = 'I will take this one';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Nitachukua hii', 'ni-ta-chu-KU-a HI-i', 'I will take this one', array['market', 'shopping']::text[], 'standard', array[]::text[], true, 'v1 chapter sokoni: At the market', 59 where not exists (select 1 from public.phrases where swahili = 'Nitachukua hii' and english = 'I will take this one');
update public.phrases set verified = true, tags = array['market', 'shopping']::text[], register = 'standard', sort_order = 60 where swahili = 'Sitaki, asante' and english = 'I don''t want it, thank you';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Sitaki, asante', 'si-TA-ki, a-SAN-te', 'I don''t want it, thank you', array['market', 'shopping']::text[], 'standard', array[]::text[], true, 'v1 chapter sokoni: At the market', 60 where not exists (select 1 from public.phrases where swahili = 'Sitaki, asante' and english = 'I don''t want it, thank you');
update public.phrases set verified = true, tags = array['safari', 'animals']::text[], register = 'standard', sort_order = 61 where swahili = 'Simba' and english = 'Lion';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Simba', 'SIM-ba', 'Lion', array['safari', 'animals']::text[], 'standard', array[]::text[], true, 'v1 chapter safari: On safari', 61 where not exists (select 1 from public.phrases where swahili = 'Simba' and english = 'Lion');
update public.phrases set verified = true, tags = array['safari', 'animals']::text[], register = 'standard', sort_order = 62 where swahili = 'Tembo / Ndovu' and english = 'Elephant';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Tembo / Ndovu', 'TEM-bo / n-DO-vu', 'Elephant', array['safari', 'animals']::text[], 'standard', array[]::text[], true, 'v1 chapter safari: On safari', 62 where not exists (select 1 from public.phrases where swahili = 'Tembo / Ndovu' and english = 'Elephant');
update public.phrases set verified = true, tags = array['safari', 'animals']::text[], register = 'standard', sort_order = 63 where swahili = 'Twiga' and english = 'Giraffe';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Twiga', 'TWI-ga', 'Giraffe', array['safari', 'animals']::text[], 'standard', array[]::text[], true, 'v1 chapter safari: On safari', 63 where not exists (select 1 from public.phrases where swahili = 'Twiga' and english = 'Giraffe');
update public.phrases set verified = true, tags = array['safari', 'animals']::text[], register = 'standard', sort_order = 64 where swahili = 'Chui' and english = 'Leopard';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Chui', 'CHU-i', 'Leopard', array['safari', 'animals']::text[], 'standard', array[]::text[], true, 'v1 chapter safari: On safari', 64 where not exists (select 1 from public.phrases where swahili = 'Chui' and english = 'Leopard');
update public.phrases set verified = true, tags = array['safari', 'animals']::text[], register = 'standard', sort_order = 65 where swahili = 'Duma' and english = 'Cheetah';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Duma', 'DU-ma', 'Cheetah', array['safari', 'animals']::text[], 'standard', array[]::text[], true, 'v1 chapter safari: On safari', 65 where not exists (select 1 from public.phrases where swahili = 'Duma' and english = 'Cheetah');
update public.phrases set verified = true, tags = array['safari', 'animals']::text[], register = 'standard', sort_order = 66 where swahili = 'Kifaru' and english = 'Rhino';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Kifaru', 'ki-FA-ru', 'Rhino', array['safari', 'animals']::text[], 'standard', array[]::text[], true, 'v1 chapter safari: On safari', 66 where not exists (select 1 from public.phrases where swahili = 'Kifaru' and english = 'Rhino');
update public.phrases set verified = true, tags = array['safari', 'animals']::text[], register = 'standard', sort_order = 67 where swahili = 'Nyati' and english = 'Buffalo';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Nyati', 'NYA-ti', 'Buffalo', array['safari', 'animals']::text[], 'standard', array[]::text[], true, 'v1 chapter safari: On safari', 67 where not exists (select 1 from public.phrases where swahili = 'Nyati' and english = 'Buffalo');
update public.phrases set verified = true, tags = array['safari', 'animals']::text[], register = 'standard', sort_order = 68 where swahili = 'Punda milia' and english = 'Zebra (striped donkey)';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Punda milia', 'PUN-da mi-LI-a', 'Zebra (striped donkey)', array['safari', 'animals']::text[], 'standard', array[]::text[], true, 'v1 chapter safari: On safari', 68 where not exists (select 1 from public.phrases where swahili = 'Punda milia' and english = 'Zebra (striped donkey)');
update public.phrases set verified = true, tags = array['safari', 'animals']::text[], register = 'standard', sort_order = 69 where swahili = 'Kiboko' and english = 'Hippo';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Kiboko', 'ki-BO-ko', 'Hippo', array['safari', 'animals']::text[], 'standard', array[]::text[], true, 'v1 chapter safari: On safari', 69 where not exists (select 1 from public.phrases where swahili = 'Kiboko' and english = 'Hippo');
update public.phrases set verified = true, tags = array['safari', 'animals']::text[], register = 'standard', sort_order = 70 where swahili = 'Nyumbu' and english = 'Wildebeest';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Nyumbu', 'NYUM-bu', 'Wildebeest', array['safari', 'animals']::text[], 'standard', array[]::text[], true, 'v1 chapter safari: On safari', 70 where not exists (select 1 from public.phrases where swahili = 'Nyumbu' and english = 'Wildebeest');
update public.phrases set verified = true, tags = array['safari', 'guide']::text[], register = 'standard', sort_order = 71 where swahili = 'Angalia!' and english = 'Look!';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Angalia!', 'an-ga-LI-a', 'Look!', array['safari', 'guide']::text[], 'standard', array[]::text[], true, 'v1 chapter safari: On safari', 71 where not exists (select 1 from public.phrases where swahili = 'Angalia!' and english = 'Look!');
update public.phrases set verified = true, tags = array['safari', 'guide', 'essential']::text[], register = 'standard', sort_order = 72 where swahili = 'Ni mnyama gani huyo?' and english = 'What animal is that?';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Ni mnyama gani huyo?', 'ni m-NYA-ma GA-ni HU-yo', 'What animal is that?', array['safari', 'guide', 'essential']::text[], 'standard', array[]::text[], true, 'v1 chapter safari: On safari', 72 where not exists (select 1 from public.phrases where swahili = 'Ni mnyama gani huyo?' and english = 'What animal is that?');
update public.phrases set verified = true, tags = array['safari', 'guide']::text[], register = 'standard', sort_order = 73 where swahili = 'Tunaweza kusimama hapa?' and english = 'Can we stop here?';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Tunaweza kusimama hapa?', 'tu-na-WE-za ku-si-MA-ma HA-pa', 'Can we stop here?', array['safari', 'guide']::text[], 'standard', array[]::text[], true, 'v1 chapter safari: On safari', 73 where not exists (select 1 from public.phrases where swahili = 'Tunaweza kusimama hapa?' and english = 'Can we stop here?');
update public.phrases set verified = true, tags = array['safari', 'guide', 'polite', 'questions']::text[], register = 'standard', sort_order = 74 where swahili = 'Naweza kupiga picha?' and english = 'May I take a photo?';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Naweza kupiga picha?', 'na-WE-za ku-PI-ga PI-cha', 'May I take a photo?', array['safari', 'guide', 'polite', 'questions']::text[], 'standard', array[]::text[], true, 'v1 chapter safari: On safari', 74 where not exists (select 1 from public.phrases where swahili = 'Naweza kupiga picha?' and english = 'May I take a photo?');
update public.phrases set verified = true, tags = array['safari', 'polite']::text[], register = 'standard', sort_order = 75 where swahili = 'Hakuna shida' and english = 'No problem';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Hakuna shida', 'ha-KU-na SHI-da', 'No problem', array['safari', 'polite']::text[], 'standard', array[]::text[], true, 'v1 chapter safari: On safari', 75 where not exists (select 1 from public.phrases where swahili = 'Hakuna shida' and english = 'No problem');
update public.phrases set verified = true, tags = array['coast', 'beach']::text[], register = 'standard', sort_order = 76 where swahili = 'Bahari' and english = 'Ocean';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Bahari', 'ba-HA-ri', 'Ocean', array['coast', 'beach']::text[], 'standard', array[]::text[], true, 'v1 chapter pwani: The coast', 76 where not exists (select 1 from public.phrases where swahili = 'Bahari' and english = 'Ocean');
update public.phrases set verified = true, tags = array['coast', 'beach']::text[], register = 'standard', sort_order = 77 where swahili = 'Pwani' and english = 'Coast, beach';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Pwani', 'PWA-ni', 'Coast, beach', array['coast', 'beach']::text[], 'standard', array[]::text[], true, 'v1 chapter pwani: The coast', 77 where not exists (select 1 from public.phrases where swahili = 'Pwani' and english = 'Coast, beach');
update public.phrases set verified = true, tags = array['coast', 'beach']::text[], register = 'standard', sort_order = 78 where swahili = 'Jahazi' and english = 'Dhow';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Jahazi', 'ja-HA-zi', 'Dhow', array['coast', 'beach']::text[], 'standard', array[]::text[], true, 'v1 chapter pwani: The coast', 78 where not exists (select 1 from public.phrases where swahili = 'Jahazi' and english = 'Dhow');
update public.phrases set verified = true, tags = array['coast', 'food']::text[], register = 'standard', sort_order = 79 where swahili = 'Samaki' and english = 'Fish';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Samaki', 'sa-MA-ki', 'Fish', array['coast', 'food']::text[], 'standard', array[]::text[], true, 'v1 chapter pwani: The coast', 79 where not exists (select 1 from public.phrases where swahili = 'Samaki' and english = 'Fish');
update public.phrases set verified = true, tags = array['coast', 'drink', 'food']::text[], register = 'standard', sort_order = 80 where swahili = 'Madafu' and english = 'Fresh coconut water';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Madafu', 'ma-DA-fu', 'Fresh coconut water', array['coast', 'drink', 'food']::text[], 'standard', array[]::text[], true, 'v1 chapter pwani: The coast', 80 where not exists (select 1 from public.phrases where swahili = 'Madafu' and english = 'Fresh coconut water');
update public.phrases set verified = true, tags = array['coast', 'smalltalk']::text[], register = 'standard', sort_order = 81 where swahili = 'Kuna joto sana leo' and english = 'It is very hot today';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Kuna joto sana leo', 'KU-na JO-to SA-na LE-o', 'It is very hot today', array['coast', 'smalltalk']::text[], 'standard', array[]::text[], true, 'v1 chapter pwani: The coast', 81 where not exists (select 1 from public.phrases where swahili = 'Kuna joto sana leo' and english = 'It is very hot today');
update public.phrases set verified = true, tags = array['coast', 'beach']::text[], register = 'standard', sort_order = 82 where swahili = 'Naweza kuogelea hapa?' and english = 'Can I swim here?';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Naweza kuogelea hapa?', 'na-WE-za ku-o-ge-LE-a HA-pa', 'Can I swim here?', array['coast', 'beach']::text[], 'standard', array[]::text[], true, 'v1 chapter pwani: The coast', 82 where not exists (select 1 from public.phrases where swahili = 'Naweza kuogelea hapa?' and english = 'Can I swim here?');
update public.phrases set verified = true, tags = array['greeting', 'coastal_greeting', 'coastal']::text[], register = 'coastal', sort_order = 83 where swahili = 'Hujambo? / Sijambo' and english = 'Are you well? / I am well';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Hujambo? / Sijambo', 'hu-JAM-bo / si-JAM-bo', 'Are you well? / I am well', array['greeting', 'coastal_greeting', 'coastal']::text[], 'coastal', array[]::text[], true, 'v1 chapter pwani: The coast', 83 where not exists (select 1 from public.phrases where swahili = 'Hujambo? / Sijambo' and english = 'Are you well? / I am well');
update public.phrases set verified = true, tags = array['greeting', 'coastal_greeting', 'coastal']::text[], register = 'coastal', sort_order = 84 where swahili = 'Habari za asubuhi?' and english = 'How is your morning?';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Habari za asubuhi?', 'ha-BA-ri za a-su-BU-hi', 'How is your morning?', array['greeting', 'coastal_greeting', 'coastal']::text[], 'coastal', array[]::text[], true, 'v1 chapter pwani: The coast', 84 where not exists (select 1 from public.phrases where swahili = 'Habari za asubuhi?' and english = 'How is your morning?');
update public.phrases set verified = true, tags = array['greeting', 'coastal_greeting', 'coastal']::text[], register = 'coastal', sort_order = 85 where swahili = 'Salama' and english = 'Peaceful, all is well';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Salama', 'sa-LA-ma', 'Peaceful, all is well', array['greeting', 'coastal_greeting', 'coastal']::text[], 'coastal', array[]::text[], true, 'v1 chapter pwani: The coast', 85 where not exists (select 1 from public.phrases where swahili = 'Salama' and english = 'Peaceful, all is well');
update public.phrases set verified = true, tags = array['farewell', 'coastal']::text[], register = 'coastal', sort_order = 86 where swahili = 'Tutaonana' and english = 'We will see each other again';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Tutaonana', 'tu-ta-o-NA-na', 'We will see each other again', array['farewell', 'coastal']::text[], 'coastal', array[]::text[], true, 'v1 chapter pwani: The coast', 86 where not exists (select 1 from public.phrases where swahili = 'Tutaonana' and english = 'We will see each other again');
update public.phrases set verified = true, tags = array['help', 'essential']::text[], register = 'standard', sort_order = 87 where swahili = 'Nisaidie, tafadhali' and english = 'Help me, please';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Nisaidie, tafadhali', 'ni-sa-i-DI-e', 'Help me, please', array['help', 'essential']::text[], 'standard', array[]::text[], true, 'v1 chapter msaada: When you need help', 87 where not exists (select 1 from public.phrases where swahili = 'Nisaidie, tafadhali' and english = 'Help me, please');
update public.phrases set verified = true, tags = array['help']::text[], register = 'standard', sort_order = 88 where swahili = 'Nimepotea' and english = 'I am lost';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Nimepotea', 'ni-me-po-TE-a', 'I am lost', array['help']::text[], 'standard', array[]::text[], true, 'v1 chapter msaada: When you need help', 88 where not exists (select 1 from public.phrases where swahili = 'Nimepotea' and english = 'I am lost');
update public.phrases set verified = true, tags = array['help', 'emergency']::text[], register = 'standard', sort_order = 89 where swahili = 'Ninaumwa' and english = 'I am sick';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Ninaumwa', 'ni-na-UM-wa', 'I am sick', array['help', 'emergency']::text[], 'standard', array[]::text[], true, 'v1 chapter msaada: When you need help', 89 where not exists (select 1 from public.phrases where swahili = 'Ninaumwa' and english = 'I am sick');
update public.phrases set verified = true, tags = array['help', 'emergency']::text[], register = 'standard', sort_order = 90 where swahili = 'Hospitali iko wapi?' and english = 'Where is the hospital?';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Hospitali iko wapi?', 'hos-pi-TA-li I-ko WA-pi', 'Where is the hospital?', array['help', 'emergency']::text[], 'standard', array[]::text[], true, 'v1 chapter msaada: When you need help', 90 where not exists (select 1 from public.phrases where swahili = 'Hospitali iko wapi?' and english = 'Where is the hospital?');
update public.phrases set verified = true, tags = array['help', 'emergency']::text[], register = 'standard', sort_order = 91 where swahili = 'Ninahitaji daktari' and english = 'I need a doctor';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Ninahitaji daktari', 'ni-na-hi-TA-ji dak-TA-ri', 'I need a doctor', array['help', 'emergency']::text[], 'standard', array[]::text[], true, 'v1 chapter msaada: When you need help', 91 where not exists (select 1 from public.phrases where swahili = 'Ninahitaji daktari' and english = 'I need a doctor');
update public.phrases set verified = true, tags = array['help', 'emergency']::text[], register = 'standard', sort_order = 92 where swahili = 'Dawa' and english = 'Medicine';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Dawa', 'DA-wa', 'Medicine', array['help', 'emergency']::text[], 'standard', array[]::text[], true, 'v1 chapter msaada: When you need help', 92 where not exists (select 1 from public.phrases where swahili = 'Dawa' and english = 'Medicine');
update public.phrases set verified = true, tags = array['help']::text[], register = 'standard', sort_order = 93 where swahili = 'Simu yangu imepotea' and english = 'My phone is lost';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Simu yangu imepotea', 'SI-mu YAN-gu i-me-po-TE-a', 'My phone is lost', array['help']::text[], 'standard', array[]::text[], true, 'v1 chapter msaada: When you need help', 93 where not exists (select 1 from public.phrases where swahili = 'Simu yangu imepotea' and english = 'My phone is lost');
update public.phrases set verified = true, tags = array['help', 'questions']::text[], register = 'standard', sort_order = 94 where swahili = 'Unaongea Kiingereza?' and english = 'Do you speak English?';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Unaongea Kiingereza?', 'u-na-on-GE-a ki-in-ge-RE-za', 'Do you speak English?', array['help', 'questions']::text[], 'standard', array[]::text[], true, 'v1 chapter msaada: When you need help', 94 where not exists (select 1 from public.phrases where swahili = 'Unaongea Kiingereza?' and english = 'Do you speak English?');
update public.phrases set verified = true, tags = array['polite']::text[], register = 'standard', sort_order = 95 where swahili = 'Pole' and english = 'Sorry (for what happened to you)';
insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order) select 'Pole', 'PO-le', 'Sorry (for what happened to you)', array['polite']::text[], 'standard', array[]::text[], true, 'v1 chapter msaada: When you need help', 95 where not exists (select 1 from public.phrases where swahili = 'Pole' and english = 'Sorry (for what happened to you)');
insert into public.proverbs (swahili, meaning, themes) select 'Heshima si utumwa', 'Respect is not servitude. Being polite costs you nothing.', array['basics']::text[] where not exists (select 1 from public.proverbs where swahili = 'Heshima si utumwa');
insert into public.proverbs (swahili, meaning, themes) select 'Mgeni njoo, mwenyeji apone', 'Let the guest come, so the host may be well.', array['airport']::text[] where not exists (select 1 from public.proverbs where swahili = 'Mgeni njoo, mwenyeji apone');
insert into public.proverbs (swahili, meaning, themes) select 'Pole pole ndio mwendo', 'Slowly, slowly is the way to travel.', array['transport']::text[] where not exists (select 1 from public.proverbs where swahili = 'Pole pole ndio mwendo');
insert into public.proverbs (swahili, meaning, themes) select 'Haraka haraka haina baraka', 'Hurry, hurry has no blessing.', array['food']::text[] where not exists (select 1 from public.proverbs where swahili = 'Haraka haraka haina baraka');
insert into public.proverbs (swahili, meaning, themes) select 'Kizuri chajiuza, kibaya chajitembeza', 'A good thing sells itself. A bad thing has to advertise.', array['market']::text[] where not exists (select 1 from public.proverbs where swahili = 'Kizuri chajiuza, kibaya chajitembeza');
insert into public.proverbs (swahili, meaning, themes) select 'Kuishi kwingi ni kuona mengi', 'To live long is to see much.', array['safari']::text[] where not exists (select 1 from public.proverbs where swahili = 'Kuishi kwingi ni kuona mengi');
insert into public.proverbs (swahili, meaning, themes) select 'Maji ya kifuu ni bahari ya chungu', 'Water in a coconut shell is an ocean to an ant.', array['coast']::text[] where not exists (select 1 from public.proverbs where swahili = 'Maji ya kifuu ni bahari ya chungu');
insert into public.proverbs (swahili, meaning, themes) select 'Kuuliza si ujinga', 'To ask is not foolishness.', array['help']::text[] where not exists (select 1 from public.proverbs where swahili = 'Kuuliza si ujinga');
insert into public.proverbs (swahili, meaning, themes) select 'Haba na haba hujaza kibaba', 'Little by little fills the measure.', array['general']::text[] where not exists (select 1 from public.proverbs where swahili = 'Haba na haba hujaza kibaba');
insert into public.proverbs (swahili, meaning, themes) select 'Mtu ni watu', 'A person is people. We are who we are because of others.', array['general']::text[] where not exists (select 1 from public.proverbs where swahili = 'Mtu ni watu');
