// The everyday dishes a traveller meets in Kenya: what each one is, how people eat it, and where it turns up.
// Exists so a first meal is not a guessing game. Names are as written on menus, with a pronunciation guide in the phrasebook's style. The notes were not part of the teacher's review.

export interface Dish {
  id: string
  name: string
  english: string
  what: string
  howToEat: string
  where: string
  pronunciation: string
  search: string
  photo?: string
}

export const DISHES: Dish[] = [
  { id: 'ugali', name: 'Ugali', english: 'Maize meal, cooked stiff', what: 'The staple. Maize flour cooked with water into a firm white block, cut or torn at the table.', howToEat: 'With the right hand. Pinch off a piece, roll it, press a dent with your thumb and scoop up stew or greens with it. It has little taste of its own; it carries the food beside it.', where: 'Everywhere, from a roadside kibanda to a hotel buffet. Almost always beside sukuma wiki or meat.', pronunciation: 'u-GA-li', search: 'ugali plate Kenya', photo: 'Plate of ugali with creamed spinach.jpg' },
  { id: 'nyama-choma', name: 'Nyama choma', english: 'Grilled meat', what: 'Goat or beef roasted slowly over charcoal, sold by weight and brought to the table on a board.', howToEat: 'By hand, with kachumbari and ugali. Order by the half kilo. It arrives already cut; take small pieces and add a pinch of salt from the board.', where: 'Weekend afternoons at a choma joint, at family gatherings, and at Carnivore in Nairobi.', pronunciation: 'NYA-ma CHO-ma', search: 'nyama choma Kenya', photo: 'Nyama choma barbeque.jpg' },
  { id: 'sukuma-wiki', name: 'Sukuma wiki', english: 'Fried greens', what: 'Shredded collard greens fried with onion and tomato. The name means "push the week", because it makes the money last.', howToEat: 'With ugali, scooped up together. It is the usual green on any plate and costs almost nothing.', where: 'Every lunch counter and home kitchen.', pronunciation: 'su-KU-ma WI-ki', search: 'sukuma wiki dish', photo: 'East African Vegetable (Sukuma wiki).jpg' },
  { id: 'chapati', name: 'Chapati', english: 'Layered flatbread', what: 'A soft, flaky wheat flatbread rolled in coils so it tears into layers. Kenyan chapati is richer than the Indian kind.', howToEat: 'Tear a piece and wrap it around beans or stew. On a good day it is the whole meal with a cup of chai.', where: 'Sundays at home, school lunches, and any cafe. Often paired with maharagwe or ndengu.', pronunciation: 'cha-PA-ti', search: 'chapati Kenya' },
  { id: 'mandazi', name: 'Mandazi', english: 'Fried dough', what: 'A lightly sweet, triangular fried bread, sometimes with coconut or cardamom. The coastal cousin is mahamri.', howToEat: 'With chai, in the morning or at four in the afternoon. Dunk it. Two are a snack, four are breakfast.', where: 'Street stalls, bus stations and every tea break.', pronunciation: 'man-DA-zi', search: 'mandazi', photo: 'Andazi.jpg' },
  { id: 'pilau', name: 'Pilau', english: 'Spiced rice', what: 'Rice cooked in stock with cumin, cardamom, cloves and cinnamon, usually with beef or goat through it.', howToEat: 'With a spoon or by hand, with kachumbari on the side to cut the richness. At a wedding or on Eid there will be a mountain of it.', where: 'The coast first, then everywhere. Fridays in many homes.', pronunciation: 'pi-LA-u', search: 'pilau Swahili rice Kenya', photo: 'Swahili Pilau.jpg' },
  { id: 'kachumbari', name: 'Kachumbari', english: 'Fresh tomato and onion salad', what: 'Tomato, red onion, chilli and coriander with lime. Sharp and cold.', howToEat: 'A spoonful beside anything hot or rich: nyama choma, pilau, mukimo. Ask for it without the chilli if you need to.', where: 'Wherever there is grilled meat.', pronunciation: 'ka-chum-BA-ri', search: 'kachumbari salad', photo: 'The "Kachumbari".jpg' },
  { id: 'githeri', name: 'Githeri', english: 'Beans and maize', what: 'Boiled maize kernels and beans, often fried up with onion, tomato and potato.', howToEat: 'With a spoon. It is filling and cheap, and a bowl at lunch keeps you going until dinner.', where: 'School kitchens, home lunches, and the central highlands especially.', pronunciation: 'gi-THE-ri', search: 'githeri Kenya' },
  { id: 'mukimo', name: 'Mukimo', english: 'Mashed potato with greens and maize', what: 'Potatoes mashed with pumpkin leaves or spinach, maize and sometimes peas, so it comes out green.', howToEat: 'With stew or nyama choma. Shape a piece with your hand or use a fork; both are fine.', where: 'Kikuyu homes and celebrations, and any restaurant serving traditional food.', pronunciation: 'mu-KI-mo', search: 'mukimo dish' },
  { id: 'chai', name: 'Chai', english: 'Tea with milk', what: 'Black tea boiled with milk and sugar, sometimes with ginger or spices. Chai means tea, not a flavour.', howToEat: 'Accept it when offered; it is how a welcome is said. It comes sweet unless you ask. Sip slowly, it is served very hot.', where: 'Every home, office and stall, from six in the morning until late.', pronunciation: 'CHA-i', search: 'Kenya tea cup' },
  { id: 'samaki', name: 'Samaki wa kupaka', english: 'Fish in coconut sauce', what: 'Grilled fish finished in a thick coconut and tamarind sauce, a coastal dish with Swahili roots.', howToEat: 'With rice or chapati. Eat around the bones with your hand or a fork. Fresh fish on the coast is often chosen from the catch before it is cooked.', where: 'Mombasa, Lamu, Diani and along the whole coast.', pronunciation: 'sa-MA-ki wa ku-PA-ka', search: 'grilled fish Kenya' },
  { id: 'viazi-karai', name: 'Viazi karai', english: 'Battered fried potatoes', what: 'Boiled potatoes dipped in a turmeric batter and deep fried, sold in paper with a fiery tamarind and chilli sauce.', howToEat: 'By hand, from the paper, dipped in the sauce. Street food, eaten standing up.', where: 'Mombasa streets and the coast in the late afternoon.', pronunciation: 'vi-A-zi ka-RA-i', search: 'Mombasa street food', photo: 'Viazi Karai.jpg' },
  { id: 'maharagwe', name: 'Maharagwe', english: 'Beans in coconut or tomato', what: 'Red beans stewed with onion and tomato, on the coast with coconut milk.', howToEat: 'With chapati or rice. The everyday vegetarian plate, and often the best thing on a cheap menu.', where: 'Every lunch counter.', pronunciation: 'ma-ha-RA-gwe', search: 'red beans stew coconut', photo: 'none' },
  { id: 'sambusa', name: 'Sambusa', english: 'Fried pastry with mince', what: 'A crisp triangle of pastry filled with spiced minced meat, or with peas and potato.', howToEat: 'By hand, hot, with a squeeze of lime. One is a snack, three with chai is supper.', where: 'Bus stations, evening streets and Ramadan tables.', pronunciation: 'sam-BU-sa', search: 'samosa' },
]
