// Turns supabase/seed/phrases.json and proverbs.json into supabase/seed.sql insert statements.
// Exists so the same seed can be pasted into the SQL editor or run by the Supabase CLI.
// Run: node scripts/buildSeedSql.ts
import { readFileSync, writeFileSync } from 'node:fs'

interface SeedPhrase {
  swahili: string
  pronunciation: string
  english: string
  tags: string[]
  register: string
  accepted_variants: string[]
  source: string
}

interface SeedProverb {
  swahili: string
  meaning: string
  themes: string[]
}

function quote(text: string): string {
  return "'" + text.replace(/'/g, "''") + "'"
}

function textArray(items: string[]): string {
  return 'array[' + items.map(quote).join(', ') + ']::text[]'
}

const phrases = JSON.parse(readFileSync('supabase/seed/phrases.json', 'utf8')) as SeedPhrase[]
const proverbs = JSON.parse(readFileSync('supabase/seed/proverbs.json', 'utf8')) as SeedProverb[]

const lines: string[] = [
  '-- Generated by scripts/buildSeedSql.ts from supabase/seed/*.json. Do not edit by hand.',
  '-- Runs again safely: rows are matched on their Swahili text.',
]
for (const [index, p] of phrases.entries()) {
  lines.push(
    `update public.phrases set verified = true, tags = ${textArray(p.tags)}, register = ${quote(p.register ?? 'standard')}, sort_order = ${index + 1} where swahili = ${quote(p.swahili)} and english = ${quote(p.english)};`,
  )
  lines.push(
    `insert into public.phrases (swahili, pronunciation, english, tags, register, accepted_variants, verified, source, sort_order)` +
      ` select ${quote(p.swahili)}, ${quote(p.pronunciation ?? '')}, ${quote(p.english)}, ${textArray(p.tags)}, ${quote(p.register ?? 'standard')}, ${textArray(p.accepted_variants ?? [])}, true, ${quote(p.source ?? '')}, ${index + 1}` +
      ` where not exists (select 1 from public.phrases where swahili = ${quote(p.swahili)} and english = ${quote(p.english)});`,
  )
}
for (const p of proverbs) {
  lines.push(
    `insert into public.proverbs (swahili, meaning, themes)` +
      ` select ${quote(p.swahili)}, ${quote(p.meaning)}, ${textArray(p.themes)}` +
      ` where not exists (select 1 from public.proverbs where swahili = ${quote(p.swahili)});`,
  )
}
writeFileSync('supabase/seed.sql', lines.join('\n') + '\n')
console.log(`Wrote ${phrases.length} phrase inserts and ${proverbs.length} proverb inserts to supabase/seed.sql`)
