// Joins every migration and the seed into one file, supabase/setup.sql, for a first time setup.
// Exists so a new Supabase project needs one paste into the SQL editor instead of five, in the right order.
// Run: node scripts/buildSetupSql.ts   (after node scripts/buildSeedSql.ts, if the seed changed)
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'

const migrations = readdirSync('supabase/migrations').filter((f) => f.endsWith('.sql')).sort()
const parts = [
  '-- Safari Njema: the whole database in one file. Generated by scripts/buildSetupSql.ts. Do not edit by hand.',
  '-- Paste this once into the Supabase SQL editor of a NEW project and press Run. It is not meant to be run twice.',
  '',
]
for (const file of migrations) {
  parts.push(`-- ===== ${file} =====`, readFileSync(`supabase/migrations/${file}`, 'utf8').trim(), '')
}
parts.push('-- ===== seed.sql: 95 reviewed phrases and 10 proverbs =====', readFileSync('supabase/seed.sql', 'utf8').trim(), '')
writeFileSync('supabase/setup.sql', parts.join('\n'))
console.log(`Wrote supabase/setup.sql from ${migrations.length} migrations and the seed.`)
